"""
metrics_utils.py — Assignment 3: Model the Patient Journey

Evaluation metrics carried over UNCHANGED from Assignments 1 and 2. You already
implemented and unit-tested these three functions in Assignment 1, so
Assignment 3 simply *imports* them instead of re-deriving AUC / F1 math a third
time. Your "from scratch" effort in this assignment goes entirely toward the
sequence-specific ideas: padding, masking, patient-level splitting, and masked
pooling.

DO NOT EDIT THIS FILE. The autograder ships its own copy; local edits here
will not change your grade and may break the local sanity check.
"""
from typing import Tuple

import numpy as np


def confusion_counts(y_true: np.ndarray, y_pred: np.ndarray) -> Tuple[int, int, int, int]:
    """Count true/false positives/negatives between predicted and true 0/1 labels.

    :return: (tp, fp, tn, fn) as plain Python ints.
    """
    y_true = np.asarray(y_true)
    y_pred = np.asarray(y_pred)
    tp = int(np.sum((y_pred == 1) & (y_true == 1)))
    fp = int(np.sum((y_pred == 1) & (y_true == 0)))
    tn = int(np.sum((y_pred == 0) & (y_true == 0)))
    fn = int(np.sum((y_pred == 0) & (y_true == 1)))
    return tp, fp, tn, fn


def precision_recall_f1(tp: int, fp: int, fn: int) -> Tuple[float, float, float]:
    """Precision, recall and F1 from confusion counts. Zero denominators -> 0.0."""
    precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0
    f1 = (
        2 * precision * recall / (precision + recall)
        if (precision + recall) > 0
        else 0.0
    )
    return precision, recall, f1


def roc_auc(y_true: np.ndarray, scores: np.ndarray) -> float:
    """Area under the ROC curve via the pairwise (Mann-Whitney U) definition.

    AUC = fraction of (positive, negative) score pairs where the positive
    score is higher (ties count as half). Assumes at least one 0 and one 1.
    """
    y_true = np.asarray(y_true)
    scores = np.asarray(scores)
    pos = scores[y_true == 1]
    neg = scores[y_true == 0]
    total = 0.0
    for score_pos in pos:
        for score_neg in neg:
            if score_pos > score_neg:
                total += 1.0
            elif score_pos == score_neg:
                total += 0.5
    return total / (len(pos) * len(neg))
