"""
test_pipeline.py — Assignment 3 local unit tests (14; 12 if PyTorch is absent).

conftest.py runs first: if any PROVIDED part of pipeline.py was modified
(load_patient_visits, PAIN_KEYWORDS, _VISIT_FEATURE_COLS), the whole run aborts
with an error. Otherwise these tests exercise the 6 functions you implement plus
get_sandbox_params(). Every stub raises ``NotImplementedError`` until you
implement it; the matching test then fails with a plain "not implemented yet"
message (no traceback). Do not edit this file.

    pytest pipeline/test_pipeline.py -v
"""
import importlib
import math
import os

import numpy as np
import pandas as pd
import pytest

pipeline = importlib.import_module(os.environ.get("PIPELINE_IMPL", "pipeline"))

FEATURE_COLS = [
    "days_since_first_visit", "pain_score_at_visit",
    "medications_at_visit", "visit_type_code",
]


def _impl(func, *args, **kwargs):
    """Call a student function; report a clean failure if it is still a stub."""
    try:
        return func(*args, **kwargs)
    except NotImplementedError:
        pass
    pytest.fail(f"{func.__name__}() is not implemented yet.", pytrace=False)


# ---------------------------------------------------------------------------
# The worked toy example — the SAME 2-patient / 3-visit table shown in the UI
# Explorer's Sequence Explorer tab. Feature column order is FEATURE_COLS.
#
#   patient A : 3 visits   patient B : 2 visits    max_len = 3
#
#   padded A = [[ 0, 2, 1, 1],   padded B = [[ 0, 1, 0, 1],
#               [30, 5, 2, 2],               [14, 4, 1, 5],
#               [61, 7, 3, 3]]               [ 0, 0, 0, 0]]   <- padding
#
#   lengths = [3, 2]      mask = [[1,1,1],
#                                 [1,1,0]]
# ---------------------------------------------------------------------------
TOY_ROWS = [
    # deliberately out of visit_number order, to test the sort
    ("A", 3, 61, 7.0, 3, 3),
    ("A", 1, 0, 2.0, 1, 1),
    ("A", 2, 30, 5.0, 2, 2),
    ("B", 2, 14, 4.0, 1, 5),
    ("B", 1, 0, 1.0, 0, 1),
]
TOY_DF = pd.DataFrame(TOY_ROWS, columns=[
    "patient_id", "visit_number", *FEATURE_COLS,
])
TOY_A = np.array([[0, 2, 1, 1], [30, 5, 2, 2], [61, 7, 3, 3]], dtype=float)
TOY_B_PADDED = np.array([[0, 1, 0, 1], [14, 4, 1, 5], [0, 0, 0, 0]], dtype=float)


# ---------------------------------------------------------------------------
# 1. pad_sequence
# ---------------------------------------------------------------------------
@pytest.mark.timeout(5)
def test_pad_sequence_pads_short_at_end():
    visits = np.array([[0, 1, 0, 1], [14, 4, 1, 5]], dtype=float)
    out = _impl(pipeline.pad_sequence, visits, 3)
    assert out.shape == (3, 4)
    np.testing.assert_array_equal(out, TOY_B_PADDED)
    assert np.all(out[2] == 0)                       # trailing row is the pad


@pytest.mark.timeout(5)
def test_pad_sequence_truncates_keeping_the_tail():
    visits = np.arange(24, dtype=float).reshape(6, 4)   # visits 0..5
    out = _impl(pipeline.pad_sequence, visits, 2)
    assert out.shape == (2, 4)
    np.testing.assert_array_equal(out, visits[-2:])     # most-recent 2 kept


@pytest.mark.timeout(5)
def test_pad_sequence_equal_length_returns_a_copy():
    visits = np.array([[1, 2, 3, 4], [5, 6, 7, 8]], dtype=float)
    out = _impl(pipeline.pad_sequence, visits, 2)
    np.testing.assert_array_equal(out, visits)
    out[0, 0] = 999
    assert visits[0, 0] == 1                            # source untouched -> copy


# ---------------------------------------------------------------------------
# 2. build_patient_sequences
# ---------------------------------------------------------------------------
@pytest.mark.timeout(10)
def test_build_patient_sequences_toy_example():
    sequences, lengths = _impl(
        pipeline.build_patient_sequences, TOY_DF, ["A", "B"], 3
    )
    assert sequences.shape == (2, 3, 4)
    np.testing.assert_array_equal(lengths, np.array([3, 2]))
    np.testing.assert_array_equal(sequences[0], TOY_A)
    np.testing.assert_array_equal(sequences[1], TOY_B_PADDED)


@pytest.mark.timeout(10)
def test_build_patient_sequences_honours_patient_id_order_and_truncation():
    sequences, lengths = _impl(
        pipeline.build_patient_sequences, TOY_DF, ["B", "A"], 2
    )
    assert sequences.shape == (2, 2, 4)
    np.testing.assert_array_equal(lengths, np.array([2, 3]))   # true counts, pre-trunc
    np.testing.assert_array_equal(sequences[0], TOY_B_PADDED[:2])
    np.testing.assert_array_equal(sequences[1], TOY_A[-2:])    # A truncated to tail


# ---------------------------------------------------------------------------
# 3. create_sequence_mask
# ---------------------------------------------------------------------------
@pytest.mark.timeout(5)
def test_create_sequence_mask_toy_example():
    mask = _impl(pipeline.create_sequence_mask, np.array([3, 2]), 3)
    assert mask.dtype == bool
    np.testing.assert_array_equal(
        mask, np.array([[True, True, True], [True, True, False]])
    )


@pytest.mark.timeout(5)
def test_create_sequence_mask_edges():
    mask = _impl(pipeline.create_sequence_mask, np.array([0, 4, 6]), 4)
    np.testing.assert_array_equal(mask[0], [False, False, False, False])
    np.testing.assert_array_equal(mask[1], [True, True, True, True])
    np.testing.assert_array_equal(mask[2], [True, True, True, True])  # length > max_len


# ---------------------------------------------------------------------------
# 4. patient_level_split
# ---------------------------------------------------------------------------
@pytest.mark.timeout(5)
def test_patient_level_split_class_balance_and_determinism():
    labels = np.array([0] * 40 + [1] * 20)
    ids = np.array([f"P{i:04d}" for i in range(60)])

    is_val = _impl(pipeline.patient_level_split, ids, labels, 0.25, seed=7)
    assert is_val.dtype == bool and is_val.shape == (60,)
    assert is_val[labels == 0].sum() == round(0.25 * 40)     # 10
    assert is_val[labels == 1].sum() == round(0.25 * 20)     # 5

    again = _impl(pipeline.patient_level_split, ids, labels, 0.25, seed=7)
    np.testing.assert_array_equal(is_val, again)
    other = _impl(pipeline.patient_level_split, ids, labels, 0.25, seed=8)
    assert not np.array_equal(is_val, other)                 # seed actually used


@pytest.mark.timeout(5)
def test_patient_level_split_matches_stratified_algorithm():
    labels = np.array([0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1])
    ids = np.array([f"P{i:04d}" for i in range(len(labels))])
    is_val = _impl(pipeline.patient_level_split, ids, labels, 0.20, seed=123)

    # reference: the Assignment 1 stratified split, applied at patient level
    rng = np.random.default_rng(123)
    expected = np.zeros(len(labels), dtype=bool)
    for cls in sorted(np.unique(labels)):
        idx = np.where(labels == cls)[0]
        shuffled = rng.permutation(idx)
        expected[shuffled[:round(0.20 * len(idx))]] = True
    np.testing.assert_array_equal(is_val, expected)


# ---------------------------------------------------------------------------
# 5. masked_mean_pooling
# ---------------------------------------------------------------------------
@pytest.mark.timeout(5)
def test_masked_mean_pooling_ignores_padding():
    seq = np.array([
        [[1., 1.], [3., 3.], [5., 5.]],
        [[2., 2.], [4., 4.], [9., 9.]],   # last step is padding, must be ignored
    ])
    mask = np.array([[True, True, True], [True, True, False]])
    pooled = _impl(pipeline.masked_mean_pooling, seq, mask)
    assert pooled.shape == (2, 2)
    np.testing.assert_allclose(pooled, [[3., 3.], [3., 3.]])


@pytest.mark.timeout(5)
def test_masked_mean_pooling_zero_real_visits_no_div_by_zero():
    seq = np.array([[[5., 5.], [5., 5.]]])
    mask = np.array([[False, False]])
    pooled = _impl(pipeline.masked_mean_pooling, seq, mask)
    np.testing.assert_allclose(pooled, [[0., 0.]])           # count treated as >= 1


# ---------------------------------------------------------------------------
# 6. build_sequence_classifier  (PyTorch — skipped if torch is absent)
# ---------------------------------------------------------------------------
def _rnn_module(model):
    """The lone nn.LSTM / nn.GRU inside a model, whichever is present."""
    import torch
    rnns = [m for m in model.modules() if isinstance(m, (torch.nn.LSTM, torch.nn.GRU))]
    assert len(rnns) == 1, "the model must contain exactly one LSTM or GRU layer"
    return rnns[0]


@pytest.mark.timeout(120)
def test_build_sequence_classifier_lstm_structure_and_forward():
    torch = pytest.importorskip("torch")
    nn = torch.nn

    model = _impl(pipeline.build_sequence_classifier, (6, 4), "lstm", 16, False)
    assert isinstance(model, nn.Module)

    rnn = _rnn_module(model)
    assert isinstance(rnn, nn.LSTM)
    assert rnn.input_size == 4 and rnn.hidden_size == 16
    assert rnn.batch_first is True
    assert rnn.bidirectional is False

    linears = [m for m in model.modules() if isinstance(m, nn.Linear)]
    assert linears[-1].out_features == 1
    assert linears[-1].in_features == 16                    # hidden_units * 1 direction
    assert any(isinstance(m, nn.Sigmoid) for m in model.modules())

    model.eval()
    with torch.no_grad():
        probs = model(torch.zeros(5, 6, 4))
    assert tuple(probs.shape) == (5, 1)
    assert bool((probs >= 0).all() and (probs <= 1).all())

    # masking: a batch that is all padding must not blow up (no div-by-zero)
    with torch.no_grad():
        z = model(torch.zeros(3, 6, 4))
    assert torch.isfinite(z).all()


@pytest.mark.timeout(120)
def test_build_sequence_classifier_gru_and_bidirectional():
    torch = pytest.importorskip("torch")
    nn = torch.nn

    gru = _impl(pipeline.build_sequence_classifier, (4, 4), "gru", 8, False)
    assert isinstance(_rnn_module(gru), nn.GRU)

    bi = _impl(pipeline.build_sequence_classifier, (4, 4), "lstm", 8, True)
    bi_rnn = _rnn_module(bi)
    assert bi_rnn.bidirectional is True
    bi_linears = [m for m in bi.modules() if isinstance(m, nn.Linear)]
    assert bi_linears[-1].in_features == 16                 # hidden_units * 2 directions
    bi.eval()
    with torch.no_grad():
        assert tuple(bi(torch.zeros(2, 4, 4)).shape) == (2, 1)

    with pytest.raises(ValueError):
        pipeline.build_sequence_classifier((4, 4), "rnn", 8, False)


# ---------------------------------------------------------------------------
# get_sandbox_params
# ---------------------------------------------------------------------------
@pytest.mark.timeout(5)
def test_get_sandbox_params_filled_in():
    """The starter values (empty student_id / cell_type, 0 hyper-parameters)
    are placeholders, not a valid answer, and fail this test on purpose until
    you copy your real values from the UI Explorer."""
    params = pipeline.get_sandbox_params()

    assert isinstance(params.get("student_id", ""), str) and params["student_id"].strip(), (
        "get_sandbox_params()['student_id'] is empty. Fill in your NetID."
    )
    assert 1 <= params.get("max_seq_len", 0) <= 6, (
        "get_sandbox_params()['max_seq_len'] must be between 1 and 6."
    )
    assert params.get("hidden_units", 0) > 0, (
        "get_sandbox_params()['hidden_units'] is 0. Fill in the value from the UI."
    )
    assert params.get("cell_type") in ("lstm", "gru"), (
        "get_sandbox_params()['cell_type'] must be 'lstm' or 'gru'."
    )
    assert params.get("val_fraction") == 0.20, (
        "get_sandbox_params()['val_fraction'] must stay 0.20."
    )
    assert math.isclose(params["val_fraction"], 0.20)
